### ISSUE TITLE
Compilation error with 0.13

### ISSUE THREAD

**Issue by supercodepoet** [vt-elixir/ja_serializer#296]
After upgrading to 0.13 from 0.12 my serializer views don't compile. I have a struct that has a label attribute:

```elixir
defmodule FontawesomeWeb.Icons.Definitions.CategoryView do
  use FontawesomeWeb, :view
  use JaSerializer.PhoenixView

  location("/api/category-definitions")

  attributes([
    :id,
    :label
  ])
end
```

when trying to compile I get:
`imported Phoenix.HTML.Form.label/2 conflicts with local function`

In Phoenix the :view has a `use Phoenix.HTML` which will import all the HTML functions for use in templates. This collision does not happen on v0.12.

Is there something I should do that I am missing?

**Comment by supercodepoet** [comment]
excellent!!! That worked perfectly. Thanks for the help!
